#!/bin/bash

echo '''
      _       _    __ _ _
   __| | ___ | |_ / _(_) | ___  ___
  / _` |/ _ \| __| |_| | |/ _ \/ __|
 | (_| | (_) | |_|  _| | |  __/\__ \
(_)__,_|\___/ \__|_| |_|_|\___||___/
'''

# Defaults
gitpath="$HOME/.dotfiles"
gitorigin="https://github.com/CryDeTaan/.dotfiles.git"

macos_config="$gitpath/macOS/macOS"
macos_brewfile="$gitpath/macOS/Brewfile"

zsh_rc="$HOME/.zshrc"
vim_rc="$HOME/.vimrc"

# Components this script knows how to setup
declare -a components=("all" "zsh" "vim" "macos_config" "macos_brew")

function show_help() {
    cat <<END
    Usage: dotfiles [option] [component]
    
    Options:
        -i, --install [component]     Install component

    Examples:
        dotfiles --install zsh
        dotfiles --install macos_config
        dotfiles -i zsh
        dotfiles -i macos_config

    Valid components:
        ${components[@]}

END
}

function install() {
    # Install routine
    prepare_git
    
    install_component=$1
    case $install_component in
      zsh)
        install_zsh
      ;;
      vim)
        install_vim
      ;;
      macos_config)
        install_macos_config
      ;;
      macos_brew)
        install_macos_brew
      ;;
    esac
}

function prepare_git() {
    # Prepare git
    if [[ ! -d $gitpath ]]; then
        git clone $gitorigin $gitpath
        return
    fi
}

install_zsh() {
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    ln -sf $gitpath/rc/zsh/zshrc $zsh_rc
}

install_vim() {
   ln -sf $gitpath/rc/vim/vimrc $vim_rc
}

install_macos_config() {
    if [[ "$OSTYPE" != darwin* ]]; then
        echo error
        exit 1
    fi

    source $macos_config

}

install_macos_brew() {
    if [[ "$OSTYPE" != darwin* ]]; then
        echo error
        exit 1
    fi

    if ! command -v brew &> /dev/null; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    brew bundle --file=$macos_brewfile

}

function main() {
    if [[ $# -gt 1 ]]; then
        case $1 in
          -i|--install)
            install $2
            ;;
          *)
            show_help
        esac
	
	exit 0
    fi

    show_help
}

main "$@"
