#!/bin/bash

echo '''
      _       _    __ _ _
   __| | ___ | |_ / _(_) | ___  ___
  / _` |/ _ \| __| |_| | |/ _ \/ __|
 | (_| | (_) | |_|  _| | |  __/\__ \
(_)__,_|\___/ \__|_| |_|_|\___||___/
'''

# Defaults
gitpath="$HOME/.dotfiles"
gitorigin="https://github.com/CryDeTaan/.dotfiles.git"
macos_config="$gitpath/macOS/macOS"

zsh_rc="$HOME/.zshrc"

function install() {
    # Install routine
    prepare_git
    
    install_component=$1
    case $install_component in
      zsh)
        install_zsh
      ;;
      macos_config)
        install_macos_config
      ;;
    esac
}

function prepare_git() {
    # Prepare git
    if [[ ! -d $gitpath ]]; then
        git clone $gitorigin $gitpath
        return
    fi
}

install_zsh() {
   ln -sf $gitpath/rc/zsh/zshrc $zsh_rc
}

install_macos_config() {
    if [[ "$OSTYPE" != darwin* ]]; then
        echo error
        exit 1
    fi

    source $macos_config

}

function main() {
    if [[ $# -gt 1 ]]; then
        case $1 in
          -i|--install)
            install $2
            ;;
          *)
            echo error
        esac
    fi
}

main "$@"
