#!/bin/bash

echo '''
      _       _    __ _ _
   __| | ___ | |_ / _(_) | ___  ___
  / _` |/ _ \| __| |_| | |/ _ \/ __|
 | (_| | (_) | |_|  _| | |  __/\__ \
(_)__,_|\___/ \__|_| |_|_|\___||___/
'''

# Defaults
gitpath="$HOME/.dotfiles"
gitorigin="https://github.com/CryDeTaan/.dotfiles.git"

macos_config="$gitpath/macOS/macOS"
macos_brewfile="$gitpath/macOS/Brewfile"

zsh_rc="$HOME/.zshrc"
vim_rc="$HOME/.vimrc"
vim_config="$HOME/.vim"

oh_my_zsh="$HOME/.oh-my-zsh"

# Components this script knows how to setup
declare -a components=("all" "zsh" "vim" "macos_config" "macos_brew" "dotfiles(configure only)")

function show_help() {
    cat <<END
    Usage: dotfiles [option] [component]
    
    Options:
        -i, --install [component]     Install component
        -c, --config [component]      Configure component

    Examples:
        dotfiles --install zsh
        dotfiles --install macos_config
        dotfiles -i zsh
        dotfiles -i macos_config


    Valid components:
        ${components[@]}

END
}

function install() {
    # Install routine
    prepare_git
    
    install_component=$1
    case $install_component in
      zsh)
        install_zsh
      ;;
      vim)
        install_vim
      ;;
      macos_config)
        install_macos_config
      ;;
      macos_brew)
        install_macos_brew
      ;;
    esac
}

function prepare_git() {
    # Prepare git
    if [[ ! -d $gitpath ]]; then
        git clone $gitorigin $gitpath
        return
    fi
}

install_zsh() {
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    ln -sf $gitpath/rc/zsh/zshrc $zsh_rc

    # Set theme
    if [[ ! -d "$oh_my_zsh/custom/themes/" ]]; then
        mkdir -p $oh_my_zsh/custom/themes/
    fi
    ln -sf $gitpath/config/zsh/oh-my-zsh/themes/crydetaan.zsh-theme $oh_my_zsh/custom/themes/crydetaan.zsh-theme

    # Add ZSH syntax highlighting plugin
    if [[ ! -d "$oh_my_zsh/custom/plugins/zsh-syntax-highlighting" ]]; then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $oh_my_zsh/custom/plugins/zsh-syntax-highlighting
    fi

    # Add ZSH auto suggestions plugin
    if [[ ! -d "$oh_my_zsh/custom/plugins/zsh-autosuggestions" ]]; then
        git clone https://github.com/zsh-users/zsh-autosuggestions.git $oh_my_zsh/custom/plugins/zsh-autosuggestions
    fi

}

install_vim() {
    ln -sf $gitpath/rc/vim/vimrc $vim_rc

    # Set theme
    if [[ ! -d "$vim_config/colors/" ]]; then
        mkdir -p $vim_config/colors/
    fi
    ln -sf $gitpath/config/vim/colour_scheme/crydetaan.vim $vim_config/colors/

    # Vundle
    if [[ ! -d "$vim_config/bundle/Vundle.vim" ]]; then
        git clone https://github.com/VundleVim/Vundle.vim.git $vim_config/bundle/Vundle.vim 
    fi

    vim +PluginInstall +qall

    # Set airline colour scheme
    if [[ ! -d "$vim_config/autoload/airline/themes/" ]]; then
        mkdir -p $vim_config/autoload/airline/themes/
    fi

    ln -sf $gitpath/config/vim/colour_scheme/crydetaan_airline.vim $vim_config/autoload/airline/themes/crydetaan.vim

}

install_macos_config() {
    if [[ "$OSTYPE" != darwin* ]]; then
        echo error
        exit 1
    fi

    source $macos_config

}

install_macos_brew() {
    if [[ "$OSTYPE" != darwin* ]]; then
        echo error
        exit 1
    fi

    if ! command -v brew &> /dev/null; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    brew bundle --file=$macos_brewfile

}

function config() {
    config_component=$1
    case $config_component in
      dotfiles)
        config_dotfiles
      ;;
      vim)
        config_vim
      ;;
    esac
 
}

function config_dotfiles() {
    vim $0
}

function config_vim() {
    vim $vim_rc
}

function main() {
    if [[ $# -gt 1 ]]; then
        case $1 in
          -i|--install)
            install $2
            ;;
          -c|--config)
            config $2
            ;;
          *)
            show_help
        esac
	
	exit 0
    fi

    show_help
}

main "$@"
