tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# GUI Apps
cask "alfred"
cask "dozer"
cask "google-chrome"
cask "hyper"
cask "iterm2"
cask "rectangle"
cask "notion"

# Terminal Apps and Tools
brew "bash" # Latest Bash version
brew "jq"
brew "mas"
brew "fd"
brew "bat"
brew "exa"

# Development
brew "php"
brew "composer"
brew "mysql"

cask "phpstorm"
cask "postman"
cask "tableplus"
cask "tinkerwell"
cask "helo"

cask "visual-studio-code"

# Security
brew "nmap"

# Mac App Store
mas "Enpass", id: 732710998
mas "Telegram", id: 747648890
