#!/bin/zsh

# MacOS configurations.
#   2022 @CryDeTaan

###############################################################################
# The Setup                                                                   #
###############################################################################

# Activates sudo mode, starts a sudo-refreshing loop, saves the loop's
# process number to $SUDO_PID, and sets a C-c trap to stop the loop on
# abrupt exit.
# Note: Failure to run stopsudo after running this will leave a stray
# https://stackoverflow.com/a/30547074
# sudo-refreshing process running.
startsudo() {
    sudo -v
    ( while true; do sudo -v; sleep 50; done; ) &
    SUDO_PID="$!"
    trap stopsudo SIGINT SIGTERM
}

# Usage: stopsudo
# Kills the sudo loop and cancels the C-c trap.
stopsudo() {
    kill "$SUDO_PID"
    wait "$SUDO_PID"
    trap - SIGINT SIGTERM
}

startsudo

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

###############################################################################
# General                                                                     #
###############################################################################
# Set computer name (as done via System Preferences → Sharing)
computer_name=$(scutil --get ComputerName)
cat <<END
This Mac currently identifies as: ${computer_name}
Do you want to update this now [y/N]?
END

read yn

if [[ "$yn" == [Yy] ]]; then
    echo "Please provide the computer name to use:"
    read computer_name

    sudo scutil --set ComputerName "$computer_name"
    sudo scutil --set HostName "$computer_name"
    sudo scutil --set LocalHostName "$computer_name"
    sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$computer_name"
fi

# Disable the sound effects on boot
sudo nvram StartupMute=%01


###############################################################################
# Menu bar and Control Centre                                                 #
###############################################################################
# Show battery in Control Centre and not in menu bar
defaults -currentHost write com.apple.controlcenter Battery -int 25

# Always show full date
defaults write com.apple.menuextra.clock ShowDate -int 1

# Removed Spotlight icon from menubar
defaults -currentHost write com.apple.Spotlight MenuItemHidden -int 1

# Hide Now Playing icon
defaults -currentHost write com.apple.controlcenter NowPlaying -int 8

# Remove Focuses icon from Menu bar.
defaults -currentHost write com.apple.controlcenter FocusModes -int 8

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 13

# Disable “natural” scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# Enable Right / Secondary click on Apple Magic Mouse
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonMode TwoButton

###############################################################################
# Finder                                                                      #
###############################################################################
# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Set $HOME as the default location for new Finder windows
# Computer     : `PfCm`
# Volume       : `PfVo`
# $HOME        : `PfHm`
# Desktop      : `PfDe`
# Documents    : `PfDo`
# All My Files : `PfAF`
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Use list view in all Finder windows by default
# Other view style.
# Icon View   : `icnv`
# List View   : `Nlsv`
# Column View : `clmv`
# Cover Flow  : `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# Show hidden files in the Finder. You can toggle the value using ⌘ + ⇧ + .
defaults write com.apple.Finder "AppleShowAllFiles" -bool "false"

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

###############################################################################
# Dock                                                                        #
###############################################################################

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Show only open applications in the Dock
defaults write com.apple.dock static-only -bool true

# "Disables" the Dock. You can toggle the Dock using ⌥ alt+⌘ cmd+d.
defaults write com.apple.dock "autohide" -bool "true"
defaults write com.apple.dock "autohide-delay" -float "1000"

# Disable Dock Bounce effects
defaults write com.apple.dock no-bouncing -bool true;

###############################################################################
# Energy saving and Screensaver                                               #
###############################################################################

# Sleep the display after 60 minutes while charging
sudo pmset -c displaysleep 60

# Set machine sleep to 15 minutes on battery
sudo pmset -b sleep 15

# Disable screensave
defaults -currentHost write com.apple.screensaver idleTime 0

###############################################################################
# Clean Up                                                                    #
###############################################################################
# Restart Affected apps and processes.
apps="Dock
Finder
cfprefsd
SystemUIServer"

for app in $apps; do
    killall "$app" &> /dev/null
done

# Stop the sudo loop
stopsudo

echo "Done. Note that some of these changes require a logout/restart to take effect."
